name: Monthly Languages

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  langs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate language stats
        uses: github-linguist/github-linguist-action@v1
        with:
          include_paths: "."
          output: "LANGUAGES.md"

      - name: Commit language stats
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update: language stats"
          file_pattern: LANGUAGES.md
