name: Monthly Languages

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  lang-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: todykranw/stirfry@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update: monthly languages"
          file_pattern: STIRFRY.md
